server.port=8081
spring.application.name=restaurants-service

spring.datasource.url=jdbc:mysql://localhost:3306/plazoleta_db
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

management.endpoints.web.exposure.include=health,info

jwt.secret=mySecretKey123456789012345678901234567890123456789012345678901234567890

messaging.service.url=http://localhost:8082/api/v1
messaging.service.timeout=30000
messaging.service.retry.attempts=3

logging.level.com.plazoleta.restaurants.adapters.driven.messaging.client=DEBUG

feign.client.config.default.connect-timeout=10000
feign.client.config.default.read-timeout=30000
